sim1:
  turtlesim1:
    ros__parameters:
      background_b: 0
      background_g: 0
      background_r: 50

turtle_control_python:
  ros__parameters:
    k_linear: 3.0     # double
    k_theta: 7.0      # double
    catch_closest_turtle: True    # Boolean

turtle_spawner_python:
  ros__parameters:
    spawn_frequency: 1   # integer

sim2:
  turtlesim2:
    ros__parameters:
      background_b: 50
      background_g: 0
      background_r: 0

turtle_control_cpp:
  ros__parameters:
    k_linear: 3.0     # double
    k_theta: 10.0     # double
    catch_closest_turtle: True   # Boolean

turtle_spawner_cpp:
  ros__parameters:
    spawn_frequency: 1   # integer